dubbo:
  application:
    name:  dubbo-consumer
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    check: false
  monitor:
    protocol: registery
  consumer:
    check:  false
    timeout: 3000
    retries: 2

server:
  port: 8080
